- .github/CODEOWNERS
- .github/workflows/stage-2-test.yaml
- .vscode/settings.json
- package-lock.json
- project.code-workspace
> CCM-5850: Review code owners

- infrastructure/terraform/components/branch/locals.tf
- infrastructure/terraform/components/branch/locals_remote_state.tf
- infrastructure/terraform/components/branch/module_amplify_branch.tf
- infrastructure/terraform/components/iam/outputs.tf
the reliance on the acct component didnt play well with the changes for the iam component being more flexible. Swap the acct lookup for an output from IAM component rather than having to declare multiple state lookups
---
> CCM-5680 Support dedicated dev env branches

- infrastructure/terraform/components/branch/locals.tf
- infrastructure/terraform/components/branch/module_amplify_branch.tf
- infrastructure/terraform/components/iam/amplify_app.tf
- infrastructure/terraform/components/iam/amplify_domain_association.tf
- infrastructure/terraform/components/iam/cognito_user_pool_client.tf
- infrastructure/terraform/components/iam/locals.tf
- infrastructure/terraform/components/iam/module_amplify_branch.tf
- infrastructure/terraform/components/iam/outputs.tf
- infrastructure/terraform/components/iam/variables.tf
renaming dns_prefix to root_domain_name because its not a prefix, if anything, its a suffix
brings consistency with the web-gateway repo for CCM-5611
---
> CCM-5611 rename resource for consistency

- .github/workflows/pr_merge.yaml
- infrastructure/terraform/components/branch/module_amplify_branch.tf
Enable autbuild on branches
fixes a mistake in build pipeline
---
> CCM-6413 enable feature auto build

- .github/workflows/manual-combine-dependabot-prs.yaml
adding a workflow to combine all outstanding dependabot PRs on a repository
---
> Adding github workflow to combine dependabot PRs

- infrastructure/terraform/components/iam/module_amplify_branch.tf
- infrastructure/terraform/components/iam/variables.tf
allows for named branches to be deployed to a named/static environment like 'dev' or 'aiva2'
---
> CCM-5521 support amplify named env branch targeting

- package-lock.json
Regenerating package-lock.json because it was malformed after a previous merge
---
> CCM-6833: Regenerate lockfile

- .github/workflows/pr_create_dynamic_env.yaml
- .github/workflows/pr_merge.yaml
- .github/workflows/release_created.yaml
- .github/workflows/trigger_internal_repo_build.yaml
- infrastructure/terraform/components/acct/route_53_record_root.tf
- infrastructure/terraform/components/app/route53_record_root.tf
- Adds --fail flag so when invocations of internal repo pipelines fail feedback is faster
- Adds mechanism for deployment on release creation
- Improves deployment to main environment on merge to main branch
- PR merge and release trigger now share a common reusable workflow
- Adds lifecycle to DNS records Amplify and Cognito are going to manage
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …
> CCM-7035 Adding auto deploy on release

- .github/actions/post-deployment/action.yaml
- .github/workflows/pr_merge.yaml
- .github/workflows/release_created.yaml
- .github/workflows/reusable_internal_repo_build.yaml
Adds a placeholder post-deployment workflow action which can be called from the internal deployment repository.
Provides an entry point for running post-deployment tests against a deployed environment.
---
> CCM-7047: Add action for post-deployment tests

- .github/workflows/pr_destroy_dynamic_env.yaml
Adding workflow for destroying the ephemeral/dynamic environments when a PR is merged
---
> CCM-3023 missing destroy pipeline

- .github/workflows/pr_destroy_dynamic_env.yaml
- infrastructure/terraform/components/branch/null_resource_initial_amplify_branch_build.tf
Fixes for destroy environment workflow
---
> CCM-8071 destroy env fixes

- infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf
adding secretsmanager perms for github ci role
---
> Adding perms for github CI role

- .github/actions/acceptance-tests/action.yaml
- .github/actions/create-lines-of-code-report/action.yaml
- .github/actions/scan-dependencies/action.yaml
- .github/workflows/cicd-1-pull-request.yaml
- .github/workflows/dispatch_internal_repo_workflow.yaml
- .github/workflows/pr_merge.yaml
- .github/workflows/release_created.yaml
- .github/workflows/stage-4-acceptance.yaml
- README.md
- infrastructure/terraform/components/sandbox/outputs.tf
- scripts/tests/accessibility.sh
- scripts/tests/ui.sh
- src/components/molecules/Footer/Footer.tsx
- tests/accessibility/.pa11y-ci.js
- tests/test-team/component-tests/signin.component.ts
Change to run acceptance tests in the nhs-notify-internal repository.
For security reasons, we don't want public repositories to hold AWS credentials. This change runs acceptance tests in the new nhs-notify-internal dispatch-acceptance-tests-dynamic-env.yaml workflow. The new nhs-notify-internal workflow will run the acceptance tests in this repository's .github/actions/acceptance-tests folder.
Test evidence has been added to [CCM-7711](https://nhsd-jira.digital.nhs.uk/browse/CCM-7711).
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data …
> CCM-7711 run acceptance tests in nhs-notify-internal workflow

- .github/actions/tfsec/action.yaml
- scripts/terraform/terraform.mk
- scripts/terraform/tfsec.sh
- Put TFSec in Hard Fail mode
- Fix tfsec config path
---
> CCM-8478 TFSec-HardFail

- infrastructure/terraform/components/app/cognito_user_pool.tf
- infrastructure/terraform/components/app/variables.tf
Adding Cognito deletion protection
---
> CCM-8529 Enable cognito delete protection

- .tool-versions
- infrastructure/terraform/components/acct/iam_role_grafana_access.tf
- infrastructure/terraform/components/acct/variables.tf
IAM Role for Grafana access from Observability account.
---
> CCM-8202: Grafana Cross Account Access

- infrastructure/terraform/components/acct/iam_policy_github_deploy_overload.tf
- infrastructure/terraform/components/acct/module_s3bucket_backup_reports.tf
- infrastructure/terraform/components/acct/outputs.tf
Adding a bucket for the backup reports which will be generated by a subsequent PR along with permissions for backup services
---
> CCM-8530 Adding Backup report bucket

- infrastructure/terraform/components/acct/module_s3bucket_lambda_function_artefacts.tf
- infrastructure/terraform/components/acct/outputs.tf
- infrastructure/terraform/components/app/cloudwatch_event_rule_backup_cognito_id.tf
- infrastructure/terraform/components/app/cloudwatch_event_target_cognito_actions.tf
- infrastructure/terraform/components/app/lambda_permission_eventbridge_backup_cognito_id_lambda.tf
- infrastructure/terraform/components/app/locals.tf
- infrastructure/terraform/components/app/module_amplify_branch.tf
- infrastructure/terraform/components/app/module_kms.tf
- infrastructure/terraform/components/app/module_lambda_backup_cognito_id.tf
- infrastructure/terraform/components/app/module_nhse_backup_vault.tf
- infrastructure/terraform/components/app/module_s3bucket_cognito_backup.tf
- infrastructure/terraform/components/app/variables.tf
- infrastructure/terraform/components/branch/module_amplify_branch.tf
- lambdas/backup-cognito-id/.gitignore
- lambdas/backup-cognito-id/README.md
- lambdas/backup-cognito-id/package-lock.json
- lambdas/backup-cognito-id/package.json
- lambdas/backup-cognito-id/src/__tests__/index.test.js
- lambdas/backup-cognito-id/src/index.js
Adding a lambda to back up users when they are modified, deleted or active
Adding a backup mechanism to backup the output of the above lambda
Backup mechanism is conditional and temporarily enabled for dev under https://github.com/NHSDigital/nhs-notify-internal/pull/219
**Do not merge before ** https://github.com/NHSDigital/nhs-notify-internal/pull/219
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …
> CCM-8530 cognito backup

- src/__tests__/components/__snapshots__/CIS2SignInButton.test.tsx.snap
- src/components/CIS2SignInButton/CIS2SignInButton.tsx
- src/styles/app.scss
- tests/accessibility/.pa11y-ci.js
- tsconfig.json
> CCM-8764: accessibility fixes

- infrastructure/terraform/components/acct/variables.tf
- infrastructure/terraform/components/app/iam_role_grafana_access.tf
- infrastructure/terraform/components/app/variables.tf
- scripts/config/pre-commit.yaml
Renaming Grafana IAM role for consistency
---
> CCM-8742: grafana iam role

- infrastructure/terraform/bin/terraform.sh
PR to handle missing tfvars files. This has been updated in the repository template so won't be overwritten again
---
> CCM-8994: Handle missing tfvars files

- infrastructure/terraform/components/acct/README.md
- infrastructure/terraform/components/acct/cloudwatch_event_rule_aws_backup_errors.tf
- infrastructure/terraform/components/acct/cloudwatch_event_rule_cloudwatch_alarms.tf
- infrastructure/terraform/components/acct/locals.tf
- infrastructure/terraform/components/acct/variables.tf
- infrastructure/terraform/components/app/iam_role_grafana_access.tf
Adds eventbridge rules to forward backup and cloudwatch alarms.
Also fixes Grafana role name.
---
> CCM-8589: Grafana Fix and Eventrules

- infrastructure/terraform/components/app/amplify_app.tf
- infrastructure/terraform/components/app/cognito_user_pool_client.tf
- infrastructure/terraform/components/app/locals.tf
- infrastructure/terraform/components/app/variables.tf
- next.config.js
PR to fix prod auth config
---
> CCM-8985: Fix auth config

- infrastructure/terraform/components/acct/README.md
- infrastructure/terraform/components/acct/outputs.tf
- infrastructure/terraform/components/app/cloudwatch_log_group_amplify.tf
- infrastructure/terraform/components/app/variables.tf
> CCM-8197: Cross Account Observability_v2

- infrastructure/terraform/components/app/README.md
- infrastructure/terraform/components/app/locals.tf
- infrastructure/terraform/components/app/module_backend_api.tf
- infrastructure/terraform/components/app/module_lambda_backup_cognito_id.tf
- infrastructure/terraform/components/app/module_public_signing_keys.tf
- infrastructure/terraform/components/sandbox/module_public_signing_keys.tf
- infrastructure/terraform/components/sandbox/variables.tf
- infrastructure/terraform/modules/backend-api/README.md
- infrastructure/terraform/modules/backend-api/cloudwatch_log_group_api_gateway_access.tf
- infrastructure/terraform/modules/backend-api/cloudwatch_log_group_api_gateway_execution.tf
- infrastructure/terraform/modules/backend-api/module_authorize_lambda.tf
- infrastructure/terraform/modules/backend-api/module_token_lambda.tf
- infrastructure/terraform/modules/backend-api/variables.tf
- infrastructure/terraform/modules/lambda-function/README.md
- infrastructure/terraform/modules/lambda-function/cloudwatch_log_subscription_filter_firehose.tf
- infrastructure/terraform/modules/lambda-function/variables.tf
- infrastructure/terraform/modules/public-signing-keys/README.md
- infrastructure/terraform/modules/public-signing-keys/module_lambda_jwks_key_rotation.tf
- infrastructure/terraform/modules/public-signing-keys/s3_bucket_policy_public_signing_keys.tf
- infrastructure/terraform/modules/public-signing-keys/variables.tf
Adding subfilter support for logs
---
> CCM-9868: splunk subscription

- infrastructure/terraform/components/app/lambda_permission_eventbridge_backup_cognito_id_lambda.tf
> CCM-10155 Fix Cognito Backup Trigger

- .github/workflows/cicd-1-pull-request.yaml
- .github/workflows/cicd-2-publish.yaml
- .github/workflows/cicd-3-deploy.yaml
- .github/workflows/dispatch_internal_repo_workflow.yaml
- .github/workflows/playwright.yml
- .github/workflows/pr_closed.yaml
- .github/workflows/pr_create_dynamic_env.yaml
- .github/workflows/pr_destroy_dynamic_env.yaml
- .github/workflows/stage-1-commit.yaml
- .github/workflows/stage-2-test.yaml
- .github/workflows/stage-3-build.yaml
- .github/workflows/stage-4-acceptance.yaml
- infrastructure/terraform/components/acct/README.md
- infrastructure/terraform/components/acct/variables.tf
- infrastructure/terraform/components/app/README.md
- infrastructure/terraform/modules/backend-api/README.md
- infrastructure/terraform/modules/public-signing-keys/README.md
Re-jigs the permissions in all workflows to ensure sane permissions are set at workflow level and then only overloaded in subsequent jobs or steps as needed. 
---
> CCM-10157: Workflows Missing Permissions Blocks

- infrastructure/terraform/components/app/cloudwatch_event_rule_backup_cognito_id.tf
- infrastructure/terraform/components/app/cloudwatch_event_target_cognito_actions.tf
- infrastructure/terraform/components/app/lambda_permission_eventbridge_backup_cognito_id_lambda.tf
- infrastructure/terraform/components/app/module_lambda_backup_cognito_id.tf
- infrastructure/terraform/components/iam/README.md
- infrastructure/terraform/components/sandbox/README.md
- infrastructure/terraform/modules/public-signing-keys/README.md
- lambdas/backup-cognito-id/README.md
- lambdas/backup-cognito-id/src/index.js
The OAUTH event wasnt an API call and had a different event structure not containing the client subject id which ultimatly broke the mechanism, Instead we're going to use the Initiate login events
---
> CCM-10155 single event trigger and handing

- .github/actions/normalize-branch-name/action.yaml
- .github/actions/test-types.json
- .github/workflows/stage-4-acceptance.yaml
- infrastructure/terraform/components/sandbox/pre.sh
- scripts/tests/test.mk
> CCM-10294 standardise cicd tests

- infrastructure/terraform/components/acct/locals.tf
Eventbus arn proj name fix
---
> CCM-11363: Eventbus arn

- infrastructure/terraform/components/app/cognito_identity_provider_cis2.tf
- infrastructure/terraform/components/app/module_backend_api.tf
- infrastructure/terraform/components/app/ssm_parameter_cis2_client_credentials.tf
- infrastructure/terraform/components/app/variables.tf
- infrastructure/terraform/modules/backend-api/module_token_lambda.tf
- infrastructure/terraform/modules/backend-api/variables.tf
- lambdas/cis2-api/src/__tests__/token-handler.test.ts
- lambdas/cis2-api/src/token-handler.ts
> CCM-9774: remove deprecated cis2 client secret auth

- .github/workflows/cicd-1-pull-request.yaml
Using concurrency in cicd request workflow to avoid parallel running jobs which can cause disruption/false results
---
> CCM-11098: Using concurrency in cicd request workflow

- .github/scripts/dispatch_internal_repo_workflow.sh
- .github/workflows/pr_closed.yaml
- .github/workflows/release_created.yaml
The static workflows done require the infraRepoName param
---
> CCM-11942 drop infrareponame from static workflow calls

- infrastructure/terraform/components/acct/module_sandbox_kms.tf
Pass providers for kms module
---
> CCM-11751: Pass providers for kms module

- infrastructure/terraform/components/app/README.md
- infrastructure/terraform/components/app/module_nhse_backup_vault.tf
- infrastructure/terraform/components/app/variables.tf
Setting retention period of backup recovery points to 31 days as per NHSE guidelines
---
> CCM-12082: Setting retention period of backup recovery points to 31 days as per NHSE guidelines
